on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install conan
        uses: conan-io/setup-conan@v1
      - name: Detect profile
        run: conan profile detect --force
      - name: Install packages
        run: conan install . --output-folder=build -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True --build=missing
      - name: Build binary
        run: cd build && ls && cmake .. -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release && cmake --build .
      - name: Publish binary
        uses: actions/upload-artifact@v6
        with:
          path: build/projectdb
